CREATE OR REPLACE FUNCTION RRHH.calcular_letra_nif(p_dni NUMBER) RETURN CHAR IS
    letras CONSTANT VARCHAR2(23) := 'TRWAGMYFPDXBNJZSQVHLCKE';
BEGIN
    RETURN SUBSTR(letras, MOD(p_dni, 23) + 1, 1);
END;
/

