CREATE OR REPLACE FUNCTION RRHH.TEST_ENCRIPTA(v_valor IN VARCHAR2) RETURN NUMBER IS
v_numero NUMBER;
BEGIN
v_numero := sys.dbms_crypto.hash(UTL_RAW.CAST_TO_RAW( '|X7GY2M43XKF3AZP176T' ),sys.dbms_crypto.hash_sh1);
RETURN 0;
EXCEPTION WHEN VALUE_ERROR THEN
RETURN 1;
END;
/

